version: '3'

services:
    # db:
    #     image: postgres:15-alpine
    #     hostname: postgresql
    #     ports:
    #         - "5432:5432"
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres
    #         PGPASSWORD: postgres
    #         POSTGRES_DB: postgres
    #         TZ: "Asia/Tokyo"
    #     volumes:
    #         - ./postgresql/data:/var/lib/postgresql/data/
    #         # - db_volume:/var/lib/postgresql
    #     # restart: always
    nginx:
        build: ./nginx
        container_name: flashcard_nginx
        hostname: flashcard_nginx
        environment:
            - TZ=Asia/Tokyo
        ports:
            - "80:80"
        depends_on:
            - frontend
    frontend:
        build: ./frontend
        container_name: flashcard_frontend
        hostname: flashcard_frontend
        volumes:
            - ./frontend/src:/usr/src/
            # - /app/node_modules
            # - /app/.next
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - BACKEND_HOST=http://flashcard_backend/api
        ports:
            - "3000:3000"
        working_dir: /usr/src/flashcards
        command: bun run dev
    backend:
        build:
            context: ./go
            target: dev
        container_name: flashcard_backend
        hostname: flashcard_backend
        ports:
            - "8000:8000"
        volumes:
            - ./go/src:/go/flashcards/

# volumes:
#     db_volume: